services:
  - type: web
    name: crypto-bot-service
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_trigger:app"
    autoDeploy: true
    envVars:
      - key: 8525986458:AAEMJePRyoVrT-myhIuOp2uA1jYXdLUmX7w
        sync: false
      - key: -1001535659036
        sync: false
      - key: AIzaSyB7vBBbvK1HSZPzGt1cxLuU1d0lQaHnpTg
        sync: false
