services:
  - type: web
    name: crypto-bot-service
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_trigger:app"
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: API_KEY
        sync: false
